sudo: required
services:
  - docker

before_install:
  - docker build -t dbhatia/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dbhatia/react-test npm test

after_success:
  - docker build -t dbhatia/multi-client -f ./client
  - docker build -t dbhatia/multi-nginx -f ./nginx
  - docker build -t dbhatia/multi-server -f ./server
  - docker build -t dbhatia/multi-worker -f ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the build images and push to docker hub
  - docker push dbhatia/multi-client
  - docker push dbhatia/multi-nginx
  - docker push dbhatia/multi-server
  - docker push dbhatia/multi-worker 
